// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccqvquzjffkcgorcivco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcXZxdXpqZmZrY2dvcmNpdmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjQ4MTUsImV4cCI6MjA1NzIwMDgxNX0.uehuvjgfReds-k5ZBMkCicf-4VevTeEKJZI9VBA_lsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);